language: node_js
dist: trusty
sudo: required
node_js: 8
install:
    - npm install -g bower
    - npm install
    - bower install
script:
    - npm run -s build
    - npm run -s clean
    - npm run -s example
